site_name: Reproschema documentation
repo_name: 'ReproNim/reproschema'
repo_url: 'https://github.com/ReproNim/reproschema'
copyright: 'CC-BY 4.0'

# This will use Material them
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'light blue'
    accent: 'light blue'

# Pages
nav:
  - Welcome: "index.md"
  - Introduction: "01_introduction.md"
  - Schema structure: "schema_structure.md"
  - How can I create a new activity and protocol?: "create_new_activity_protocol.md"
  - Testing your schema and collecting data: "testing_using_schema.md"
  - Schemas properties: "97_schema_properties.md"
  - FAQ: "98_FAQ.md"
  - Glossary: "99_glossary.md"
  - About this doc: "100_about_this_doc.md"


# list of extension
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
